In [7]:
## Importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [8]:
%pwd

'c:\\E drive\\Previous data\\Project\\52 project\\7. Telecom Customer Churn Prediction'

In [9]:
## Reading the file

df = pd.read_csv('C:\\E drive\\Previous data\\Project\\52 project\\7. Telecom Customer Churn Prediction\\Customer-Churn (1).csv')

In [10]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [11]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.463013
Yes    26.536987
Name: count, dtype: float64

## **Churn Rate**: 26.53%

- Which means, 26.53% of the customers churn out of this telecom company

In [12]:
## Divide data into X and y - X (Independent features), y(Dependent variable)

# Define y (target variable)
y = df['Churn']

# Define X (features) by dropping 'customerID' and 'Churn'
X = df.drop(columns=['customerID', 'Churn'])

# Optional: Verify the shapes
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (7043, 19)
Shape of y: (7043,)

## Train Test Split

In [13]:
X = pd.get_dummies(X, drop_first=True)
y = df['Churn'].map({'No': 0, 'Yes': 1})

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Model Building

In [15]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [16]:
y_pred_dt = model_dt.predict(X_test)

In [17]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.84      0.87      0.86      1053
           1       0.58      0.51      0.54       356

    accuracy                           0.78      1409
   macro avg       0.71      0.69      0.70      1409
weighted avg       0.77      0.78      0.78      1409

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

## Initial Insights

- Base model has a accuracy of 76% which is not reliable because of the imbalanced dataset
- TotalCharges needs to be a float/int type (Data Cleaning)
- Need to perform Feature Scaling

## Data Cleaning

In [19]:
telco_data = df.copy()

In [20]:
telco_data.TotalCharges = pd.to_numeric(telco_data.TotalCharges, errors='coerce')

In [21]:
telco_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.8 MB

In [22]:
telco_data.loc[telco_data['TotalCharges'].isnull() == True]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [23]:
telco_data.dropna(how='any', inplace=True)

In [24]:
telco_data.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   str
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   str
 4   Dependents        7032 non-null   str
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   str
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   str
 9   OnlineSecurity    7032 non-null   str
 10  OnlineBackup      7032 non-null   str
 11  DeviceProtection  7032 non-null   str
 12  TechSupport       7032 non-null   str
 13  StreamingTV       7032 non-null   str
 14  StreamingMovies   7032 non-null   str
 15  Contract          7032 non-null   str
 16  PaperlessBilling  7032 non-null   str
 17  PaymentMethod     7032 non-null   str
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.9 MB

In [25]:
telco_data.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [26]:
telco_data.tenure.max()

np.int64(72)

In [27]:
import pandas as pd

# Define the bin edges (0 to 72, stepping by 12 months)
bins = [0, 12, 24, 36, 48, 60, 72]

# Define the labels for each bin
labels = ['1-12', '13-24', '25-36', '37-48', '49-60', '61-72']

# Create the new binned column
telco_data['tenure_bin'] = pd.cut(telco_data['tenure'], bins=bins, labels=labels, include_lowest=True)

# Optional: Check the result
print(telco_data[['tenure', 'tenure_bin']].head(10))
print(telco_data['tenure_bin'].value_counts().sort_index())

   tenure tenure_bin
0       1       1-12
1      34      25-36
2       2       1-12
3      45      37-48
4       2       1-12
5       8       1-12
6      22      13-24
7      10       1-12
8      28      25-36
9      62      61-72
tenure_bin
1-12     2175
13-24    1024
25-36     832
37-48     762
49-60     832
61-72    1407
Name: count, dtype: int64

In [28]:
telco_data.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_bin
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1-12
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,25-36
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1-12
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,37-48
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1-12

In [29]:
## Divide data into X and y - X (Independent features), y(Dependent variable)

# Define y (target variable)
y = telco_data['Churn']

# Define X (features) by dropping 'customerID' and 'Churn'
X = telco_data.drop(columns=['customerID', 'Churn', 'tenure'])

# Optional: Verify the shapes
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (7032, 19)
Shape of y: (7032,)

In [30]:
X

,gender,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,tenure_bin
0,Female,0,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,1-12
1,Male,0,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,25-36
2,Male,0,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1-12
3,Male,0,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,37-48
4,Female,0,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,13-24
7039,Female,0,Yes,Yes,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,61-72
7040,Female,0,Yes,Yes,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,1-12
7041,Male,1,Yes,No,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,1-12
7042,Male,0,No,No,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,61-72

In [31]:
X = pd.get_dummies(X, drop_first=True)
y = telco_data['Churn'].map({'No': 0, 'Yes': 1})

In [32]:
X

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,...,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_bin_13-24,tenure_bin_25-36,tenure_bin_37-48,tenure_bin_49-60,tenure_bin_61-72
0,0,29.85,29.85,False,True,False,False,True,False,False,...,False,True,False,True,False,False,False,False,False,False
1,0,56.95,1889.50,True,False,False,True,False,False,False,...,False,False,False,False,True,False,True,False,False,False
2,0,53.85,108.15,True,False,False,True,False,False,False,...,False,True,False,False,True,False,False,False,False,False
3,0,42.30,1840.75,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,False,False,False,True,False,False,True,...,False,True,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,84.80,1990.50,True,True,True,True,False,True,False,...,False,True,False,False,True,True,False,False,False,False
7039,0,103.20,7362.90,False,True,True,True,False,True,True,...,False,True,True,False,False,False,False,False,False,True
7040,0,29.60,346.45,False,True,True,False,True,False,False,...,False,True,False,True,False,False,False,False,False,False
7041,1,74.40,306.60,True,True,False,True,False,True,True,...,False,True,False,False,True,False,False,False,False,False
7042,0,105.65,6844.50,True,False,False,True,False,False,True,...,True,True,False,False,False,False,False,False,False,True

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Feature Scaling

In [34]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [35]:
model_dt2 = DecisionTreeClassifier()
model_dt2.fit(X_train, y_train)

y_pred_dt2 = model_dt2.predict(X_test)

In [36]:
print(classification_report(y_test, y_pred_dt2))

              precision    recall  f1-score   support

           0       0.79      0.80      0.80      1009
           1       0.48      0.45      0.47       398

    accuracy                           0.70      1407
   macro avg       0.63      0.63      0.63      1407
weighted avg       0.70      0.70      0.70      1407

## Feature Scaling - MinMaxScaler

In [37]:
mms = MinMaxScaler()
X_train_mms = mms.fit_transform(X_train)
X_test_mms = mms.transform(X_test)

In [38]:
model_dt3 = DecisionTreeClassifier()
model_dt3.fit(X_train_mms, y_train)

y_pred_dt3 = model_dt3.predict(X_test_mms)

In [39]:
print(classification_report(y_test, y_pred_dt3))

              precision    recall  f1-score   support

           0       0.79      0.81      0.80      1009
           1       0.48      0.46      0.47       398

    accuracy                           0.71      1407
   macro avg       0.64      0.63      0.63      1407
weighted avg       0.70      0.71      0.71      1407

## SMOTEENN () [UpSampling + ENN)

In [40]:
from imblearn.combine import SMOTEENN

In [41]:
sm = SMOTEENN()
X_train_resampled, y_train_resampled = sm.fit_resample(X_train, y_train)

In [42]:
model_dt_smoteenn = DecisionTreeClassifier()
model_dt_smoteenn.fit(X_train_resampled, y_train_resampled)

y_pred_dt_smoteenn = model_dt_smoteenn.predict(X_test)

In [43]:
print(classification_report(y_test, y_pred_dt_smoteenn))

              precision    recall  f1-score   support

           0       0.88      0.71      0.79      1009
           1       0.51      0.75      0.61       398

    accuracy                           0.72      1407
   macro avg       0.69      0.73      0.70      1407
weighted avg       0.77      0.72      0.73      1407

In [44]:
model_rf_smoteenn = RandomForestClassifier(n_estimators=500)
model_rf_smoteenn.fit(X_train_resampled, y_train_resampled)

y_pred_rf_smoteenn = model_rf_smoteenn.predict(X_test)

In [45]:
print(classification_report(y_test, y_pred_rf_smoteenn))

              precision    recall  f1-score   support

           0       0.89      0.73      0.80      1009
           1       0.53      0.77      0.63       398

    accuracy                           0.74      1407
   macro avg       0.71      0.75      0.71      1407
weighted avg       0.79      0.74      0.75      1407

## XGBoost without SMOTEENN

In [46]:
from xgboost import XGBClassifier

# Initialize and train the XGBoost model
model_xgb = XGBClassifier(random_state=42)  # random_state for reproducibility
model_xgb.fit(X_train, y_train)

# Make predictions on the test set
y_pred_xgb = model_xgb.predict(X_test)

In [47]:
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84      1009
           1       0.61      0.48      0.54       398

    accuracy                           0.77      1407
   macro avg       0.71      0.68      0.69      1407
weighted avg       0.75      0.77      0.76      1407

## XGBoost with SMOTEENN

In [48]:
from xgboost import XGBClassifier

# Initialize and train the XGBoost model
model_xgb_smoteenn = XGBClassifier(random_state=42)  # random_state for reproducibility
model_xgb_smoteenn.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred_xgb_smoteenn = model_xgb_smoteenn.predict(X_test)

In [49]:
print(classification_report(y_test, y_pred_xgb_smoteenn))

              precision    recall  f1-score   support

           0       0.88      0.73      0.80      1009
           1       0.52      0.75      0.61       398

    accuracy                           0.73      1407
   macro avg       0.70      0.74      0.70      1407
weighted avg       0.78      0.73      0.74      1407

## XGBoost with SMOTE

In [50]:
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from collections import Counter

# Check class distribution before SMOTE
print("Before SMOTE:", Counter(y_train))

# Apply SMOTE to the training data only
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

# Check class distribution after SMOTE
print("After SMOTE:", Counter(y_train_smote))

# Initialize and train the XGBoost model on resampled data
model_xgb_smote = XGBClassifier(random_state=42)
model_xgb_smote.fit(X_train_smote, y_train_smote)

# Make predictions on the original test set (unchanged)
y_pred_xgb_smote = model_xgb_smote.predict(X_test)

Before SMOTE: Counter({0: 4154, 1: 1471})
After SMOTE: Counter({0: 4154, 1: 4154})

In [51]:
print(classification_report(y_test, y_pred_xgb_smote))

              precision    recall  f1-score   support

           0       0.83      0.86      0.84      1009
           1       0.61      0.55      0.58       398

    accuracy                           0.77      1407
   macro avg       0.72      0.70      0.71      1407
weighted avg       0.77      0.77      0.77      1407

In [52]:
from imblearn.over_sampling import ADASYN
from xgboost import XGBClassifier
from collections import Counter

# Check original distribution
print("Before ADASYN:", Counter(y_train))

# Apply ADASYN to training data only
adasyn = ADASYN(random_state=42)
X_train_adasyn, y_train_adasyn = adasyn.fit_resample(X_train, y_train)

# Check new distribution
print("After ADASYN:", Counter(y_train_adasyn))

# Train XGBoost on ADASYN-resampled data
model_xgb_adasyn = XGBClassifier(random_state=42)
model_xgb_adasyn.fit(X_train_adasyn, y_train_adasyn)

# Predict on the original test set
y_pred_xgb_adasyn = model_xgb_adasyn.predict(X_test)

# Evaluate
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred_xgb_adasyn))
print("\nClassification Report:\n", classification_report(y_test, y_pred_xgb_adasyn))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb_adasyn))

Before ADASYN: Counter({0: 4154, 1: 1471})
After ADASYN: Counter({0: 4154, 1: 4082})
Accuracy: 0.7668798862828714

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.86      0.84      1009
           1       0.60      0.52      0.56       398

    accuracy                           0.77      1407
   macro avg       0.71      0.69      0.70      1407
weighted avg       0.76      0.77      0.76      1407


Confusion Matrix:
 [[872 137]
 [191 207]]

In [53]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Calculate scale_pos_weight (ratio of negative to positive class)
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
print(f"scale_pos_weight: {scale_pos_weight:.2f}")

# Train XGBoost with scale_pos_weight
model_xgb_weighted = XGBClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric='logloss'  # avoids warnings
)

model_xgb_weighted.fit(X_train, y_train)
y_pred_weighted = model_xgb_weighted.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred_weighted))
print("\nClassification Report:\n", classification_report(y_test, y_pred_weighted))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_weighted))

scale_pos_weight: 2.82
Accuracy: 0.744136460554371

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.79      0.82      1009
           1       0.54      0.62      0.58       398

    accuracy                           0.74      1407
   macro avg       0.69      0.71      0.70      1407
weighted avg       0.76      0.74      0.75      1407


Confusion Matrix:
 [[800 209]
 [151 247]]

In [54]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# Calculate the weight for the positive (minority) class
# Common approach: weight_positive = negative_count / positive_count
negative_count = (y_train == 0).sum()
positive_count = (y_train == 1).sum()
weight_positive = negative_count / positive_count if positive_count > 0 else 1
print(f"Negative class count: {negative_count}")
print(f"Positive class count: {positive_count}")
print(f"Weight for positive class: {weight_positive:.2f}")

# Create sample weights: higher weight for minority class
sample_weight = np.where(y_train == 1, weight_positive, 1.0)

# Train AdaBoost with sample weights
model_ada_weighted = AdaBoostClassifier(
    n_estimators=50,  # default, you can tune
    random_state=42
)

model_ada_weighted.fit(X_train, y_train, sample_weight=sample_weight)

# Predict and evaluate
y_pred_ada_weighted = model_ada_weighted.predict(X_test)

print("AdaBoost with sample weighting - Accuracy:", accuracy_score(y_test, y_pred_ada_weighted))
print("\nClassification Report:\n", classification_report(y_test, y_pred_ada_weighted))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_ada_weighted))

Negative class count: 4154
Positive class count: 1471
Weight for positive class: 2.82
AdaBoost with sample weighting - Accuracy: 0.7619047619047619

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.76      0.82      1009
           1       0.56      0.78      0.65       398

    accuracy                           0.76      1407
   macro avg       0.73      0.77      0.73      1407
weighted avg       0.80      0.76      0.77      1407


Confusion Matrix:
 [[763 246]
 [ 89 309]]

## **Hyper Parameter Optimization**

In [55]:
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier

param_grid = {
    'max_depth': [3, 4, 5, 6, 7],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'n_estimators': [100, 200, 300, 400],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.2],
    'scale_pos_weight': [1, scale_pos_weight]  # try both balanced and weighted
}

xgb = XGBClassifier(random_state=42, eval_metric='logloss')

# Use 'f1' or 'recall' scoring since churn is imbalanced
search = RandomizedSearchCV(
    xgb,
    param_grid,
    n_iter=50,
    cv=5,
    scoring='f1',  # or 'recall' if catching churn is priority
    random_state=42,
    n_jobs=-1
)

search.fit(X_train, y_train)

print("Best parameters:", search.best_params_)
print("Best CV F1 score:", search.best_score_)

# Use best model
best_model = search.best_estimator_
y_pred_best = best_model.predict(X_test)
print("\nTest Classification Report:\n", classification_report(y_test, y_pred_best))

Best parameters: {'subsample': 0.8, 'scale_pos_weight': np.float64(2.823929299796057), 'n_estimators': 200, 'min_child_weight': 5, 'max_depth': 4, 'learning_rate': 0.05, 'gamma': 0.2, 'colsample_bytree': 0.8}
Best CV F1 score: 0.6363939326527394

Test Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.74      0.81      1009
           1       0.53      0.74      0.62       398

    accuracy                           0.74      1407
   macro avg       0.71      0.74      0.71      1407
weighted avg       0.78      0.74      0.75      1407

In [56]:
# Save this model

import joblib

# Save the best model to a .pkl file
joblib.dump(best_model, 'best_xgboost_churn_model.pkl')

print("Best model successfully saved as 'best_xgboost_churn_model.pkl'")

Best model successfully saved as 'best_xgboost_churn_model.pkl'

## Trying out few more techniques

In [57]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(
    class_weight='balanced',
    random_state=42,
    n_estimators=300,
    max_depth=6
)
model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.89      0.73      0.80      1009
           1       0.53      0.78      0.63       398

    accuracy                           0.74      1407
   macro avg       0.71      0.75      0.72      1407
weighted avg       0.79      0.74      0.75      1407

In [58]:
from catboost import CatBoostClassifier

model_cat = CatBoostClassifier(
    auto_class_weights='Balanced',  # or 'SqrtBalanced'
    verbose=0,
    random_state=42
)
model_cat.fit(X_train, y_train)
y_pred_cat = model_cat.predict(X_test)
print(classification_report(y_test, y_pred_cat))

              precision    recall  f1-score   support

           0       0.87      0.76      0.82      1009
           1       0.55      0.72      0.62       398

    accuracy                           0.75      1407
   macro avg       0.71      0.74      0.72      1407
weighted avg       0.78      0.75      0.76      1407

In [59]:
from lightgbm import LGBMClassifier

model_lgb = LGBMClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42
)
model_lgb.fit(X_train, y_train)
y_pred_lgb = model_lgb.predict(X_test)
print(classification_report(y_test, y_pred_lgb))

[LightGBM] [Info] Number of positive: 1471, number of negative: 4154
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004523 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 606
[LightGBM] [Info] Number of data points in the train set: 5625, number of used features: 34
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.261511 -> initscore=-1.038129
[LightGBM] [Info] Start training from score -1.038129
              precision    recall  f1-score   support

           0       0.86      0.76      0.81      1009
           1       0.53      0.69      0.60       398

    accuracy                           0.74      1407
   macro avg       0.70      0.73      0.71      1407
weighted avg       0.77      0.74      0.75      1407

c:\E drive\Previous data\Project\52 project\7. Telecom Customer Churn Prediction\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

## **Optuna fine tuning**

In [60]:
import optuna
from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, make_scorer

def objective(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 1),  # L1 regularization
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 2), # L2 regularization
        'scale_pos_weight': trial.suggest_categorical('scale_pos_weight', [1, scale_pos_weight]),
        'random_state': 42,
        'eval_metric': 'logloss'
    }

    model = XGBClassifier(**params)

    # Use F1 for minority class as scorer
    f1_scorer = make_scorer(f1_score, average='binary', pos_label=1)
    score = cross_val_score(model, X_train, y_train, cv=5, scoring=f1_scorer, n_jobs=-1).mean()

    return score

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)  # Increase trials for better results

print("Best parameters:", study.best_params)
print("Best CV F1 score:", study.best_value)

# Train final model with best params
best_model_optuna = XGBClassifier(**study.best_params)
best_model_optuna.fit(X_train, y_train)
y_pred_optuna = best_model_optuna.predict(X_test)
print(classification_report(y_test, y_pred_optuna))

c:\E drive\Previous data\Project\52 project\7. Telecom Customer Churn Prediction\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-07-09 11:01:14,537] A new study created in memory with name: no-name-6f3e8f3e-2559-4a3b-816b-d2af2aa46062
[I 2026-07-09 11:01:21,288] Trial 0 finished with value: 0.6139340288858554 and parameters: {'max_depth': 6, 'learning_rate': 0.07456603628535877, 'n_estimators': 616, 'subsample': 0.7286543087517892, 'colsample_bytree': 0.617115841358379, 'min_child_weight': 10, 'gamma': 0.1858734544157697, 'reg_alpha': 0.43262299860971065, 'reg_lambda': 1.075966087485276, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 0 with value: 0.6139340288858554.
[I 2026-07-09 11:01:30,257] Trial 1 finished with value: 0.5903182286191071 and parameters: {'max_depth': 5, 'learning_rate': 0.1250603942405451, 'n_estimators': 867, 'subsample': 0.7710428560052573, 'colsample_bytree': 0.6587804488297837, 'min_child_weight': 1, 'gamma': 0.19086930628106658, 'reg_alpha': 0.31970123318787846, 'reg_lambda': 1.0514943538789558, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 0 with value: 0.6139340288858554.
[I 2026-07-09 11:01:35,273] Trial 2 finished with value: 0.6341811614290794 and parameters: {'max_depth': 3, 'learning_rate': 0.028471038369891847, 'n_estimators': 653, 'subsample': 0.6244784181101498, 'colsample_bytree': 0.8888995080858673, 'min_child_weight': 6, 'gamma': 0.19677909458364234, 'reg_alpha': 0.7078444178222288, 'reg_lambda': 0.26757713094645474, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 2 with value: 0.6341811614290794.
[I 2026-07-09 11:01:44,552] Trial 3 finished with value: 0.6310648129643414 and parameters: {'max_depth': 9, 'learning_rate': 0.010475506359010355, 'n_estimators': 715, 'subsample': 0.6835124660527088, 'colsample_bytree': 0.8372542410257913, 'min_child_weight': 10, 'gamma': 0.03952565821212928, 'reg_alpha': 0.8251739700109324, 'reg_lambda': 1.9427014174546071, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 2 with value: 0.6341811614290794.
[I 2026-07-09 11:01:46,668] Trial 4 finished with value: 0.5910750120886731 and parameters: {'max_depth': 5, 'learning_rate': 0.038037997262318685, 'n_estimators': 210, 'subsample': 0.6787547419421209, 'colsample_bytree': 0.6503140017797358, 'min_child_weight': 5, 'gamma': 0.15269979378607085, 'reg_alpha': 0.2825479235583245, 'reg_lambda': 1.0624796208859402, 'scale_pos_weight': 1}. Best is trial 2 with value: 0.6341811614290794.
[I 2026-07-09 11:01:51,384] Trial 5 finished with value: 0.5572944121911193 and parameters: {'max_depth': 9, 'learning_rate': 0.1663200956027267, 'n_estimators': 375, 'subsample': 0.7512501550219683, 'colsample_bytree': 0.7720103426423324, 'min_child_weight': 9, 'gamma': 0.4175270377347445, 'reg_alpha': 0.031497946205530925, 'reg_lambda': 1.5198224480270321, 'scale_pos_weight': 1}. Best is trial 2 with value: 0.6341811614290794.
[I 2026-07-09 11:02:01,685] Trial 6 finished with value: 0.5479168409349251 and parameters: {'max_depth': 9, 'learning_rate': 0.1183843253709371, 'n_estimators': 693, 'subsample': 0.8048000076570057, 'colsample_bytree': 0.8168295044719021, 'min_child_weight': 3, 'gamma': 0.07880647237029903, 'reg_alpha': 0.41858054996666383, 'reg_lambda': 0.4675542105063075, 'scale_pos_weight': 1}. Best is trial 2 with value: 0.6341811614290794.
[I 2026-07-09 11:02:08,910] Trial 7 finished with value: 0.593158597475056 and parameters: {'max_depth': 8, 'learning_rate': 0.12288002944923444, 'n_estimators': 838, 'subsample': 0.9343549814712997, 'colsample_bytree': 0.6574084624052914, 'min_child_weight': 10, 'gamma': 0.32013517756281606, 'reg_alpha': 0.6252006407483885, 'reg_lambda': 0.006553565097548786, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 2 with value: 0.6341811614290794.
[I 2026-07-09 11:02:16,154] Trial 8 finished with value: 0.571090320648173 and parameters: {'max_depth': 9, 'learning_rate': 0.029763985876735757, 'n_estimators': 613, 'subsample': 0.8317250113932105, 'colsample_bytree': 0.8270383736263859, 'min_child_weight': 10, 'gamma': 0.4600009516945664, 'reg_alpha': 0.09215044550768592, 'reg_lambda': 0.21702481193669332, 'scale_pos_weight': 1}. Best is trial 2 with value: 0.6341811614290794.
[I 2026-07-09 11:02:21,477] Trial 9 finished with value: 0.5761329492654512 and parameters: {'max_depth': 5, 'learning_rate': 0.019510690609686077, 'n_estimators': 520, 'subsample': 0.6114480640274902, 'colsample_bytree': 0.8941135029938718, 'min_child_weight': 3, 'gamma': 0.47353482714673006, 'reg_alpha': 0.5185027772720235, 'reg_lambda': 0.32441794230396526, 'scale_pos_weight': 1}. Best is trial 2 with value: 0.6341811614290794.
[I 2026-07-09 11:02:22,611] Trial 10 finished with value: 0.6216833828097001 and parameters: {'max_depth': 3, 'learning_rate': 0.29168657027883715, 'n_estimators': 101, 'subsample': 0.9754608503603883, 'colsample_bytree': 0.9996396082608652, 'min_child_weight': 7, 'gamma': 0.31427275332742577, 'reg_alpha': 0.9500760167842938, 'reg_lambda': 0.6652713025124086, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 2 with value: 0.6341811614290794.
[I 2026-07-09 11:02:29,291] Trial 11 finished with value: 0.6345473557586403 and parameters: {'max_depth': 3, 'learning_rate': 0.010772927330997693, 'n_estimators': 762, 'subsample': 0.6024066763796594, 'colsample_bytree': 0.9295534365322956, 'min_child_weight': 7, 'gamma': 0.0014286306224680911, 'reg_alpha': 0.8196120399692052, 'reg_lambda': 1.994281663007103, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 11 with value: 0.6345473557586403.
[I 2026-07-09 11:02:37,246] Trial 12 finished with value: 0.6366109465341572 and parameters: {'max_depth': 3, 'learning_rate': 0.010885132372086907, 'n_estimators': 998, 'subsample': 0.6078600374324081, 'colsample_bytree': 0.9396434384348142, 'min_child_weight': 7, 'gamma': 0.00025913076198183504, 'reg_alpha': 0.7146402506429644, 'reg_lambda': 1.881931664670594, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 12 with value: 0.6366109465341572.
[I 2026-07-09 11:02:44,098] Trial 13 finished with value: 0.6364498012512358 and parameters: {'max_depth': 3, 'learning_rate': 0.011343840377149313, 'n_estimators': 972, 'subsample': 0.6012545620348033, 'colsample_bytree': 0.9911172686945998, 'min_child_weight': 8, 'gamma': 0.0005504841496673637, 'reg_alpha': 0.925192682500524, 'reg_lambda': 1.9249585381038519, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 12 with value: 0.6366109465341572.
[I 2026-07-09 11:02:52,054] Trial 14 finished with value: 0.6303491111897798 and parameters: {'max_depth': 4, 'learning_rate': 0.01645696613256694, 'n_estimators': 974, 'subsample': 0.6819609013753856, 'colsample_bytree': 0.9988831877752321, 'min_child_weight': 8, 'gamma': 0.07870914976261369, 'reg_alpha': 0.9866385053715145, 'reg_lambda': 1.6264101079071493, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 12 with value: 0.6366109465341572.
[I 2026-07-09 11:02:59,869] Trial 15 finished with value: 0.6301737027144136 and parameters: {'max_depth': 4, 'learning_rate': 0.016537920921442514, 'n_estimators': 997, 'subsample': 0.6428720070983922, 'colsample_bytree': 0.9504357906740732, 'min_child_weight': 5, 'gamma': 0.0044885071410294426, 'reg_alpha': 0.7877623467661382, 'reg_lambda': 1.6735811740310207, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 12 with value: 0.6366109465341572.
[I 2026-07-09 11:03:10,168] Trial 16 finished with value: 0.6278364344626791 and parameters: {'max_depth': 7, 'learning_rate': 0.010211448761483784, 'n_estimators': 887, 'subsample': 0.6617822728810161, 'colsample_bytree': 0.9461593196331664, 'min_child_weight': 8, 'gamma': 0.11139992797101311, 'reg_alpha': 0.6432024982528243, 'reg_lambda': 1.384065829875857, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 12 with value: 0.6366109465341572.
[I 2026-07-09 11:03:17,787] Trial 17 finished with value: 0.6339024363437333 and parameters: {'max_depth': 4, 'learning_rate': 0.019861019956264252, 'n_estimators': 928, 'subsample': 0.7025289975863748, 'colsample_bytree': 0.9012465323391208, 'min_child_weight': 8, 'gamma': 0.05961736866785637, 'reg_alpha': 0.9220484448633409, 'reg_lambda': 1.8239175034741848, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 12 with value: 0.6366109465341572.
[I 2026-07-09 11:03:23,712] Trial 18 finished with value: 0.6291887420011629 and parameters: {'max_depth': 3, 'learning_rate': 0.045271854819884695, 'n_estimators': 803, 'subsample': 0.6012315375278021, 'colsample_bytree': 0.9517730460880418, 'min_child_weight': 6, 'gamma': 0.12756312766481, 'reg_alpha': 0.7190277270119596, 'reg_lambda': 1.4374788405854657, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 12 with value: 0.6366109465341572.
[I 2026-07-09 11:03:31,403] Trial 19 finished with value: 0.6303179552680294 and parameters: {'max_depth': 4, 'learning_rate': 0.014682730080489809, 'n_estimators': 980, 'subsample': 0.6491704526316278, 'colsample_bytree': 0.8592366487426986, 'min_child_weight': 4, 'gamma': 0.2494445884131057, 'reg_alpha': 0.578392664639828, 'reg_lambda': 1.2991997785526053, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 12 with value: 0.6366109465341572.
[I 2026-07-09 11:03:40,246] Trial 20 finished with value: 0.6189258512886973 and parameters: {'max_depth': 6, 'learning_rate': 0.025095981422854016, 'n_estimators': 901, 'subsample': 0.8578419598164649, 'colsample_bytree': 0.7442141453759671, 'min_child_weight': 7, 'gamma': 0.03695634687433939, 'reg_alpha': 0.8801691372028011, 'reg_lambda': 1.776959475867239, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 12 with value: 0.6366109465341572.
[I 2026-07-09 11:03:46,601] Trial 21 finished with value: 0.6353189885126731 and parameters: {'max_depth': 3, 'learning_rate': 0.012441459150144683, 'n_estimators': 758, 'subsample': 0.6009390856711588, 'colsample_bytree': 0.9310437800362477, 'min_child_weight': 7, 'gamma': 0.007849433286708073, 'reg_alpha': 0.802278986432211, 'reg_lambda': 1.998342039228808, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 12 with value: 0.6366109465341572.
[I 2026-07-09 11:03:53,025] Trial 22 finished with value: 0.6322692804547267 and parameters: {'max_depth': 3, 'learning_rate': 0.013405138343390586, 'n_estimators': 499, 'subsample': 0.6401221573491649, 'colsample_bytree': 0.9679443116030253, 'min_child_weight': 6, 'gamma': 0.00512880893649169, 'reg_alpha': 0.7350576568100058, 'reg_lambda': 1.8693607421301457, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 12 with value: 0.6366109465341572.
[I 2026-07-09 11:04:01,942] Trial 23 finished with value: 0.6370373129907706 and parameters: {'max_depth': 4, 'learning_rate': 0.012985012494085225, 'n_estimators': 784, 'subsample': 0.7139257299105985, 'colsample_bytree': 0.9163551865427695, 'min_child_weight': 9, 'gamma': 0.08173881581911775, 'reg_alpha': 0.8547669115655638, 'reg_lambda': 1.7153471511527703, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 23 with value: 0.6370373129907706.
[I 2026-07-09 11:04:08,812] Trial 24 finished with value: 0.6316910559932369 and parameters: {'max_depth': 4, 'learning_rate': 0.02212338992655082, 'n_estimators': 800, 'subsample': 0.7179513742507435, 'colsample_bytree': 0.9762335153676502, 'min_child_weight': 9, 'gamma': 0.103653170355921, 'reg_alpha': 0.8973912674930383, 'reg_lambda': 1.7308949588936926, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 23 with value: 0.6370373129907706.
[I 2026-07-09 11:04:16,931] Trial 25 finished with value: 0.6305170421152744 and parameters: {'max_depth': 5, 'learning_rate': 0.014622204584392581, 'n_estimators': 889, 'subsample': 0.8815077870529652, 'colsample_bytree': 0.9104572847328437, 'min_child_weight': 9, 'gamma': 0.062140050039933496, 'reg_alpha': 0.8581048378801281, 'reg_lambda': 1.24121773187374, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 23 with value: 0.6370373129907706.
[I 2026-07-09 11:04:25,837] Trial 26 finished with value: 0.5836282194912352 and parameters: {'max_depth': 4, 'learning_rate': 0.018093090580650433, 'n_estimators': 944, 'subsample': 0.763059557971681, 'colsample_bytree': 0.8857071619530748, 'min_child_weight': 8, 'gamma': 0.13474309061453202, 'reg_alpha': 0.99491304431349, 'reg_lambda': 1.5666239839994975, 'scale_pos_weight': 1}. Best is trial 23 with value: 0.6370373129907706.
[I 2026-07-09 11:04:35,800] Trial 27 finished with value: 0.6112940832712509 and parameters: {'max_depth': 6, 'learning_rate': 0.05041162051560506, 'n_estimators': 997, 'subsample': 0.8003716232174264, 'colsample_bytree': 0.7808856031012031, 'min_child_weight': 9, 'gamma': 0.04760980341639182, 'reg_alpha': 0.6736666264162405, 'reg_lambda': 1.780334278659665, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 23 with value: 0.6370373129907706.
[I 2026-07-09 11:04:46,759] Trial 28 finished with value: 0.6279947305542872 and parameters: {'max_depth': 10, 'learning_rate': 0.012306918015750694, 'n_estimators': 824, 'subsample': 0.7166286215907677, 'colsample_bytree': 0.8681248480938234, 'min_child_weight': 8, 'gamma': 0.09129545501330648, 'reg_alpha': 0.7615878807879732, 'reg_lambda': 1.61253452268725, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 23 with value: 0.6370373129907706.
[I 2026-07-09 11:04:52,071] Trial 29 finished with value: 0.6282087159657339 and parameters: {'max_depth': 5, 'learning_rate': 0.03362324360260409, 'n_estimators': 546, 'subsample': 0.7396286889432285, 'colsample_bytree': 0.9818328078609364, 'min_child_weight': 9, 'gamma': 0.16358549221736657, 'reg_alpha': 0.5338051866068315, 'reg_lambda': 1.2281961366955696, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 23 with value: 0.6370373129907706.
[I 2026-07-09 11:04:56,356] Trial 30 finished with value: 0.6306438068940933 and parameters: {'max_depth': 6, 'learning_rate': 0.023124902607450537, 'n_estimators': 404, 'subsample': 0.6336391864699954, 'colsample_bytree': 0.9163622010438912, 'min_child_weight': 5, 'gamma': 0.22555167858536962, 'reg_alpha': 0.9048616719210948, 'reg_lambda': 1.8595007207012038, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 23 with value: 0.6370373129907706.
[I 2026-07-09 11:05:01,599] Trial 31 finished with value: 0.6372141350635754 and parameters: {'max_depth': 3, 'learning_rate': 0.012763134216221132, 'n_estimators': 742, 'subsample': 0.6624483005235712, 'colsample_bytree': 0.9301532298503956, 'min_child_weight': 7, 'gamma': 0.03120383271427037, 'reg_alpha': 0.7797606828592308, 'reg_lambda': 1.9975749812630845, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 31 with value: 0.6372141350635754.
[I 2026-07-09 11:05:06,326] Trial 32 finished with value: 0.6311309770059832 and parameters: {'max_depth': 3, 'learning_rate': 0.010051495079793018, 'n_estimators': 603, 'subsample': 0.6636132782434656, 'colsample_bytree': 0.9643472472009209, 'min_child_weight': 7, 'gamma': 0.03794637475854702, 'reg_alpha': 0.7664425145920131, 'reg_lambda': 1.896508242700798, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 31 with value: 0.6372141350635754.
[I 2026-07-09 11:05:12,209] Trial 33 finished with value: 0.6352810918262561 and parameters: {'max_depth': 4, 'learning_rate': 0.013083842086455794, 'n_estimators': 724, 'subsample': 0.6253074845647326, 'colsample_bytree': 0.9291947999420824, 'min_child_weight': 1, 'gamma': 0.030527790467529143, 'reg_alpha': 0.8577369536003655, 'reg_lambda': 0.8870708195252005, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 31 with value: 0.6372141350635754.
[I 2026-07-09 11:05:18,363] Trial 34 finished with value: 0.6358329667773439 and parameters: {'max_depth': 3, 'learning_rate': 0.015959292402173607, 'n_estimators': 864, 'subsample': 0.6987183624837825, 'colsample_bytree': 0.8704043428835142, 'min_child_weight': 6, 'gamma': 0.09920869279621504, 'reg_alpha': 0.6999235509325024, 'reg_lambda': 1.4756622760810005, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 31 with value: 0.6372141350635754.
[I 2026-07-09 11:05:23,473] Trial 35 finished with value: 0.6338543388801764 and parameters: {'max_depth': 3, 'learning_rate': 0.012168160467685188, 'n_estimators': 665, 'subsample': 0.6634375460223274, 'colsample_bytree': 0.9321644789269204, 'min_child_weight': 8, 'gamma': 0.06519628005535713, 'reg_alpha': 0.6129104084831929, 'reg_lambda': 1.710002986637053, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 31 with value: 0.6372141350635754.
[I 2026-07-09 11:05:29,665] Trial 36 finished with value: 0.6287814474242176 and parameters: {'max_depth': 4, 'learning_rate': 0.02676493907545764, 'n_estimators': 756, 'subsample': 0.6929386354247593, 'colsample_bytree': 0.848318841777663, 'min_child_weight': 6, 'gamma': 0.031240196396228576, 'reg_alpha': 0.9341848909441267, 'reg_lambda': 1.9303637488195329, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 31 with value: 0.6372141350635754.
[I 2026-07-09 11:05:37,943] Trial 37 finished with value: 0.5812483339320794 and parameters: {'max_depth': 5, 'learning_rate': 0.019018058071487612, 'n_estimators': 921, 'subsample': 0.6295909712141378, 'colsample_bytree': 0.7025145151975654, 'min_child_weight': 10, 'gamma': 0.16753039964713273, 'reg_alpha': 0.8188991119814131, 'reg_lambda': 1.7040920309942227, 'scale_pos_weight': 1}. Best is trial 31 with value: 0.6372141350635754.
[I 2026-07-09 11:05:44,709] Trial 38 finished with value: 0.6358708095254404 and parameters: {'max_depth': 3, 'learning_rate': 0.011733416519534337, 'n_estimators': 842, 'subsample': 0.7359484402268417, 'colsample_bytree': 0.9835080172745411, 'min_child_weight': 7, 'gamma': 0.02446746509611484, 'reg_alpha': 0.4470179588981266, 'reg_lambda': 1.8337341405947591, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 31 with value: 0.6372141350635754.
[I 2026-07-09 11:05:52,790] Trial 39 finished with value: 0.5687710160311115 and parameters: {'max_depth': 4, 'learning_rate': 0.08250166770558742, 'n_estimators': 656, 'subsample': 0.7837565632301609, 'colsample_bytree': 0.8863203448176583, 'min_child_weight': 9, 'gamma': 0.1275885999341856, 'reg_alpha': 0.6809772345673181, 'reg_lambda': 1.5424317341259814, 'scale_pos_weight': 1}. Best is trial 31 with value: 0.6372141350635754.
[I 2026-07-09 11:06:01,662] Trial 40 finished with value: 0.6351162477925133 and parameters: {'max_depth': 3, 'learning_rate': 0.014481224956830985, 'n_estimators': 943, 'subsample': 0.6744622573434292, 'colsample_bytree': 0.618805210171979, 'min_child_weight': 10, 'gamma': 0.07875529033993887, 'reg_alpha': 0.18422081133801993, 'reg_lambda': 1.9840250035029772, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 31 with value: 0.6372141350635754.
[I 2026-07-09 11:06:10,350] Trial 41 finished with value: 0.6342266166433734 and parameters: {'max_depth': 3, 'learning_rate': 0.01137674694836391, 'n_estimators': 837, 'subsample': 0.732114872942998, 'colsample_bytree': 0.9757273042955422, 'min_child_weight': 7, 'gamma': 0.03000511338140009, 'reg_alpha': 0.3905630066483442, 'reg_lambda': 1.8228973788695721, 'scale_pos_weight': np.float64(2.823929299796057)}. Best is trial 31 with value: 0.6372141350635754.

Best parameters: {'max_depth': 3, 'learning_rate': 0.012408112705913436, 'n_estimators': 945, 'subsample': 0.6406694499483817, 'colsample_bytree': 0.7438767127277963, 'min_child_weight': 7, 'gamma': 0.0026463975747151227, 'reg_alpha': 0.3913803670445234, 'reg_lambda': 0.5753669933423992, 'scale_pos_weight': np.float64(2.823929299796057)}
Best CV F1 score: 0.6380237941277043
              precision    recall  f1-score   support

           0       0.89      0.75      0.81      1009
           1       0.54      0.76      0.63       398

    accuracy                           0.75      1407
   macro avg       0.71      0.75      0.72      1407
weighted avg       0.79      0.75      0.76      1407

In [61]:
# Save this model

import joblib

# Save the best model to a .pkl file
joblib.dump(best_model_optuna, 'best_optuna_churn_model.pkl')

print("Best model successfully saved as 'best_optuna_churn_model.pkl'")

Best model successfully saved as 'best_optuna_churn_model.pkl'

In [62]:
# Save this model

import joblib

# Save the best model to a .pkl file
joblib.dump(model_ada_weighted, 'ada_boost_churn_model.pkl')

print("Best model successfully saved as 'ada_boost_churn_model.pkl'")

Best model successfully saved as 'ada_boost_churn_model.pkl'